name: Rodar Bot Discord

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  push:
    branches:
      - main  # Executa o workflow sempre que houver um push na branch main
  workflow_dispatch:  # Permite disparar manualmente o workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Executa a ação em um ambiente Ubuntu

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Defina a versão do Python que seu bot usa

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala as dependências do seu bot

    - name: Rodar o bot
      run: python bot.py  # Substitua por seu arquivo principal, no caso "bot.py"
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  # Aqui você adiciona seu token de Discord de forma segura
